# Generated by Django 3.0.2 on 2021-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KVM_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=10, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('link_scraped', models.IntegerField(null=True)),
                ('link_resolved', models.IntegerField(null=True)),
                ('days_to_reply', models.IntegerField(null=True)),
                ('average_tat', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=12, null=True)),
                ('time_utilised_ws', models.IntegerField(null=True)),
                ('time_utilised_rs', models.IntegerField(null=True)),
                ('time_utilised_rp', models.IntegerField(null=True)),
                ('time_utilised_mt', models.IntegerField(null=True)),
                ('time_utilised_ml', models.IntegerField(null=True)),
            ],
        ),
    ]
